### ISSUE TITLE
In merito alla traduzione di Variant Space Octet

### ISSUE THREAD

**Issue by wingsofbahamut** [divergenceshifter/divergenceshifter.github.io#1]
Innanzitutto ti faccio i miei complimenti per l'ottimo lavoro svolto con la traduzione, volevo segnalarti però che il nome Neidhardt per Takumi, anche se utilizzato spesso nei titoli ufficiali, è sbagliato. Infatti nelle CG di Chaos;Head si legge che il nome del personaggio è "KnightHart", ti consiglierei perciò di sostituirlo con quello per una maggiore fedeltà al titolo originale.

Grazie mille per il tuo tempo, appena possibile continuerò a giocare il titolo ed in caso a segnalarti eventuali errori. :)

**Comment by KyouinDev** [comment]
Grazie per il consiglio! La versione aggiornata è stata caricata nel setup [v1.1](https://github.com/divergenceshifter/divergenceshifter.github.io/releases/tag/octet)
