### ISSUE TITLE
Neidhardt

### ISSUE THREAD

**Issue by Steniichi** [divergenceshifter/divergenceshifter.github.io#2]
Bel lavoro, solo "Neidhardt", dovrebbe essere "KnightHart", è un errore di traduzione degli inglesi purtroppo, non so neanche da dove gli sia venuta. Questo username è del protagonista di Chaos;Head e c'è una CG che testimonia quello che dico. Ora continuo a giocare e vedo se trovo altro, comunque GG.
![エンスーギミック](https://user-images.githubusercontent.com/60004423/72616763-e2d7cf00-3937-11ea-85e9-e2e8e2c389e8.png)

**Comment by KyouinDev** [comment]
Grazie per il consiglio! La versione aggiornata è stata caricata nel setup [v1.1](https://github.com/divergenceshifter/divergenceshifter.github.io/releases/tag/octet)
