### ISSUE TITLE
Visualizzazione opzioni di scelta

### ISSUE THREAD

**Issue by Jirachu** [divergenceshifter/divergenceshifter.github.io#3]
Il gioco mi sta piacendo un sacco, purtroppo continuo a fare game over perché non visualizzo più di 5 opzioni di scelta dei comandi da poter scrivere. E' normale? Dove trovo una guida?

**Comment by KyouinDev** [comment]
Salve! Purtroppo sì, la visual novel di per sé è complessa, basandosi molto sul dedurre i comandi. Attualmente vi è una seconda riga di comandi, visibile con il tasto SHIFT, ma non tutti i comandi sono suggeriti in queste due liste. Ho appena aggiunto questo suggerimento nel setup [v1.1](https://github.com/divergenceshifter/divergenceshifter.github.io/releases/tag/octet), giusto prima di iniziare. Per il resto... non credo possa far molto, spero sia abbastanza!
